### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Zilla31** [Deadolus/ha-beurer#10]
Hello,

I can not setup successfully to the Beurer TL100

Can you help.

I do have the following log:

2023-12-21 23:06:55.683 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header":{"from":"/app/713917-4ff91d5cdd67bceefa86cfa3ac0ef0e6/subscribe","messageId":"f65a88821d768216b753efd4dbede6fe","method":"GET","namespace":"Appliance.System.Ability","payloadVersion":1,"sign":"d4f5582d3a12e7cd260f5d38122ea720","timestamp":1703196406,"triggerSrc":"Android","uuid":"2009302754750858850148e1e9351fa9"},"payload":{}}' sent to device uuid 2009302754750858850148e1e9351fa9. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu-3.meross.com:443.
2023-12-21 23:06:55.684 WARNING (MainThread) [meross_iot.manager] Device Puit (2009302754750858850148e1e9351fa9) is online, but timeout occurred when fetching its abilities. 
/bin/sh: /opt/vc/bin/vcgencmd: not found
2023-12-21 23:06:58.204 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 127): /opt/vc/bin/vcgencmd measure_temp
2023-12-21 23:06:58.904 DEBUG (MainThread) [custom_components.beurer] Discovered devices: [BLEDevice(D4:AD:FC:70:00:A7, GBK_H61A0_00A7), BLEDevice(34:25:B4:DC:77:E1, GXDC77E1), BLEDevice(F4:05:8B:ED:5E:EB, Galaxy Watch Active (3FF5) LE), BLEDevice(BC:C7:DA:C0:C1:4A, TP358 (C14A)), BLEDevice(F0:99:19:BA:E5:4F, F0-99-19-BA-E5-4F), BLEDevice(E4:5F:01:11:08:5F, E4-5F-01-11-08-5F), BLEDevice(A6:D7:3C:96:70:32, XP-5200 Series), BLEDevice(7A:CE:94:65:54:1D, 7A-CE-94-65-54-1D), BLEDevice(5E:5F:BF:BC:42:F3, 5E-5F-BF-BC-42-F3), BLEDevice(57:4C:42:9E:A1:34, TL100_A134), BLEDevice(4A:E1:74:F8:5E:A2, 4A-E1-74-F8-5E-A2), BLEDevice(5E:7F:25:2B:68:72, 5E-7F-25-2B-68-72), BLEDevice(7E:17:C3:FA:E5:A5, 7E-17-C3-FA-E5-A5), BLEDevice(79:FB:2D:21:B0:B6, 79-FB-2D-21-B0-B6)]
2023-12-21 23:06:58.905 DEBUG (MainThread) [custom_components.beurer] Going to update from config flow
2023-12-21 23:06:58.905 DEBUG (MainThread) [custom_components.beurer] Going to connect to device
2023-12-21 23:06:58.909 DEBUG (MainThread) [custom_components.beurer] Going to connect to device
2023-12-21 23:06:58.945 DEBUG (MainThread) [custom_components.beurer] Traceback (most recent call last):
  File "/config/custom_components/beurer/beurer.py", line 268, in connect
    await self._device.connect(timeout=20)
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 298, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 249, in connect
    assert_reply(reply)
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Operation already in progress

2023-12-21 23:06:58.946 ERROR (MainThread) [custom_components.beurer] Error connecting: [org.bluez.Error.Failed] Operation already in progress
2023-12-21 23:06:58.955 DEBUG (MainThread) [custom_components.beurer] Traceback (most recent call last):
  File "/config/custom_components/beurer/beurer.py", line 268, in connect
    await self._device.connect(timeout=20)
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 298, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 249, in connect
    assert_reply(reply)
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] br-connection-canceled

2023-12-21 23:06:58.955 ERROR (MainThread) [custom_components.beurer] Error connecting: [org.bluez.Error.Failed] br-connection-canceled
2023-12-21 23:06:58.959 INFO (MainThread) [custom_components.beurer] Was not able to connect to device for updates
2023-12-21 23:06:58.959 DEBUG (MainThread) [custom_components.beurer] Disconnecting
2023-12-21 23:06:58.959 WARNING (MainThread) [custom_components.beurer] No async update function provided: None
2023-12-21 23:06:58.963 DEBUG (MainThread) [custom_components.beurer] Finished updating from config flow, light is False
2023-12-21 23:06:58.964 DEBUG (MainThread) [custom_components.beurer] Turning on
2023-12-21 23:06:58.964 DEBUG (MainThread) [custom_components.beurer] Going to connect to device
2023-12-21 23:07:08.642 WARNING (MainThread) [custom_components.localtuya.common] [bfb...xpa] Failed to connect to 192.168.1.25: [Errno 113] Connect call failed ('192.168.1.25', 6668)
2023-12-21 23:07:15.486 WARNING (event_thread_0) [sucks] Ping did not reach VacBot. Will retry.
2023-12-21 23:07:18.971 DEBUG (MainThread) [custom_components.beurer] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 209, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 399, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/beurer/beurer.py", line 268, in connect
    await self._device.connect(timeout=20)
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 298, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 146, in connect
    async with async_timeout(timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

2023-12-21 23:07:18.971 ERROR (MainThread) [custom_components.beurer] Error connecting: 
2023-12-21 23:07:18.972 DEBUG (MainThread) [custom_components.beurer] Going to connect to device

**Comment by pyalot** [comment]
Abandoned project obviously
